(function () {
  const DAY_MS = 24 * 60 * 60 * 1000;

  function addDays(isoDate, days) {
    const date = new Date(`${isoDate}T12:00:00`);
    return new Date(date.getTime() + days * DAY_MS).toISOString().slice(0, 10);
  }

  function makeWeeks(firstDate, topics = []) {
    return Array.from({ length: 15 }, (_, index) => {
      const source = topics[index];
      const normalized = typeof source === "string" ? { topic: source } : (source || {});
      return {
        week: index + 1,
        date: addDays(firstDate, index * 7),
        topic: normalized.topic || `${index + 1}주차 수업`,
        detail: normalized.detail || "",
        materials: normalized.materials || "",
        assignment: normalized.assignment || "",
        note: "",
        reviewed: false
      };
    });
  }

  const courses = [
    {
      id: "python",
      order: 1,
      name: "파이썬응용",
      shortName: "파이썬응용",
      type: "major",
      color: "#8ca8ff",
      professor: "정은화",
      professorInfo: "",
      location: "본부 210",
      code: "0966201",
      section: "",
      credits: "3학점 · 이론 2 · 실습 2",
      meetingLabel: "화요일 2-4교시",
      meetings: [{ day: 2, start: 10, end: 13, room: "본부 210" }],
      description: "파이썬 언어로 다양한 프로젝트를 수행하고, 실제 상황에서 활용할 수 있는 응용 프로그램과 데이터 처리 능력을 기르는 실습 중심 전공 수업입니다.",
      goals: ["파이썬 문법과 객체지향 개념을 응용 프로그램 개발에 활용", "NumPy와 Pandas를 이용한 데이터 처리·분석 능력 습득", "파이썬으로 전공 문제를 해결하는 창의적 사고와 실무 역량 개발"],
      textbooks: ["수업용 PPT 자료", "으뜸 파이썬 · 생능출판사", "점프 투 파이썬 · 박응용", "데이터 분석 with 파이썬 · 한빛아카데미"],
      grading: [{ label: "출석", value: 10 }, { label: "교과목 역량평가", value: 90 }],
      policies: ["결석 누계가 4주(16시간) 이상이면 출석 F 처리", "실습 위주·문제기반 방식으로 진행", "역량평가 내부 비중: 창의융합적사고 10%, 전공문제해결 45%, 전공지식적용 45%", "15주차 창의융합적사고·전공지식적용 실기 평가"],
      links: [],
      weeks: makeWeeks("2026-09-01", [
        { topic: "파이썬 소개와 개발 환경", detail: "파이썬의 특징을 살펴보고 개발 환경을 설정합니다." },
        { topic: "변수·상수·연산자", detail: "파이썬 기초 문법을 실습합니다." },
        { topic: "제어문과 반복문", assignment: "실습과제 1" },
        { topic: "자료형과 함수", detail: "자료형과 함수 작성법을 실습합니다." },
        { topic: "객체지향 프로그래밍 1", detail: "클래스, 인스턴스, 생성자" },
        { topic: "객체지향 프로그래밍 2", detail: "상속", assignment: "실습과제 2" },
        { topic: "NumPy 활용", detail: "배열 기반 데이터 처리" },
        { topic: "Pandas 소개와 활용", assignment: "전공문제해결능력 과제 평가 여부 확인" },
        { topic: "시리즈와 데이터프레임" },
        { topic: "인덱스와 파일 저장·열기", assignment: "실습과제 3" },
        { topic: "파일 확인과 데이터 선택", detail: "기본 선택과 loc 등" },
        { topic: "결측치·정렬·수정" },
        { topic: "함수 적용과 그룹화" },
        { topic: "Pandas를 이용한 데이터 활용 1", assignment: "실습과제 4" },
        { topic: "Pandas를 이용한 데이터 활용 2", detail: "실기 중심 종합 활용" }
      ]),
      examMemo: "8주차에 전공문제해결능력 과제 평가가 안내되어 있습니다. 15주차에는 파이썬 프로그램을 활용하는 실기 평가가 예정되어 있으며 세부 범위는 교수 공지 후 수정하세요.",
      courseMemo: ""
    },
    {
      id: "startup",
      order: 2,
      name: "창업과 네트워킹",
      shortName: "창업과 네트워킹",
      type: "general",
      color: "#d8a2ad",
      professor: "이경호",
      professorInfo: "",
      location: "목양 502",
      code: "0981802",
      section: "",
      credits: "2학점 · 이론 2",
      meetingLabel: "화요일 5교시",
      meetings: [{ day: 2, start: 13, end: 14, room: "목양 502" }],
      description: "전반기에는 창업과 기업가 사례를, 후반기에는 기업윤리와 사회적 책임을 학습합니다. 발표·토론과 PBL을 통해 창업 아이디어 및 윤리적 의사결정 능력을 기릅니다.",
      goals: ["기업과 창업, 기업과 사회의 관계 이해", "경영윤리의 개념과 필요성·주요 이론 학습", "글로벌 기업의 윤리경영 사례를 분석하고 직업윤리 함양"],
      textbooks: ["산업생태계를 위한 플랫폼경영 · 강병영", "제3판 윤리경영 - 이론과 실제 · 최만기·김영복", "기업윤리 · 이종영", "정의란 무엇인가 · 마이클 샌델"],
      grading: [{ label: "출석", value: 20 }, { label: "중간고사", value: 30 }, { label: "기말·개인 레포트", value: 30 }, { label: "발표·토론", value: 20 }],
      policies: ["모바일 출석 및 수업 영상 출석으로 자동 계산", "동영상 전체 미시청 또는 토론 참여 미비 시 지각 처리", "중간·기말 미응시 시 재시험을 부여하고 재시험 성적은 70% 반영", "주차별 포트폴리오와 발표·토론 참여를 평가"],
      links: [],
      weeks: makeWeeks("2026-09-01", [
        "오리엔테이션 · 기업의 이해와 평가방법",
        "국내 창업 사례 · 국내 기업가 중심",
        "해외 창업 사례 · 해외 기업가 중심",
        "환경 변화와 벤처 창업",
        "벤처 창업 전략",
        { topic: "기회의 탐색과 아이디어 개발", assignment: "나만의 창업 아이디어 기획·제출 준비" },
        "기업과 사회의 관계 · 윤리의 정의와 유형",
        { topic: "중간고사 · 윤리경영의 개념과 기초", assignment: "창업 아이디어 제출 여부 확인" },
        "윤리경영 이론과 발전 과정",
        "윤리경영의 체계와 구성",
        { topic: "윤리경영 시스템 구축과 운용", assignment: "윤리적 의사결정 사례 연구" },
        "생산관리 윤리",
        "인사관리 윤리",
        "마케팅관리 윤리 · 재무·회계 윤리",
        { topic: "기말고사 · 윤리경영의 방향과 과제", assignment: "개인 레포트 제출 여부 확인" }
      ]),
      examMemo: "8주차 중간고사는 윤리경영 이해, 15주차 기말고사는 윤리경영의 전망과 과제를 평가하는 논술형 시험입니다. 기말고사와 개인 레포트가 합산 30%이며 세부 배점은 공지 확인이 필요합니다.",
      courseMemo: ""
    },
    {
      id: "ai-citizen",
      order: 3,
      name: "AI 인성과 글로벌시티즌",
      shortName: "AI 인성과 글로벌시티즌",
      type: "general",
      color: "#cf92b5",
      professor: "이은선",
      professorInfo: "",
      location: "진리 509",
      code: "3205101",
      section: "",
      credits: "2학점 · 이론 2",
      meetingLabel: "화요일 6교시",
      meetings: [{ day: 2, start: 14, end: 15, room: "진리 509" }],
      description: "AI 시대에 인간 고유의 가치와 S-PIPES 인성을 성찰하고, 세계시민으로서 국제사회 문제를 윤리적으로 해결하는 역량을 프로젝트로 기르는 수업입니다.",
      goals: ["기계와 차별화되는 인간의 내면 역량 학습", "지구촌 공동체 문제를 이해하고 AI를 윤리적으로 활용", "사회공헌 역량과 책임 있는 세계시민 행동 개발", "학습 내용을 개인·팀 프로젝트와 현장에 적용"],
      textbooks: ["S-PIPES 인성개발리더십 · 이계능 외", "인성전공융합론 · 이계능 외", "S-PIPES Theory · 이계능"],
      grading: [{ label: "출석", value: 20 }, { label: "기말고사", value: 20 }, { label: "프로젝트", value: 50 }, { label: "상담·기타", value: 10 }],
      policies: ["스마트출결로 평가하며 출석 규정을 준수", "역량평가 50% 미만 시 재평가 기회 1회", "프로젝트는 진단·설계, 실행·문제해결, 성찰·통합 단계로 진행", "팀 활동·특강·상담·코칭 참여가 평가에 포함"],
      links: [],
      weeks: makeWeeks("2026-09-01", [
        "오리엔테이션 · 수업 목적과 평가 안내",
        "AI 시대의 S-PIPES 인성과 글로벌 시티즌",
        "BKD-SA 교육 프로그램 설계 1",
        "BKD-SA 교육 프로그램 설계 2",
        "S-PIPES 인성과 국격 페스티벌",
        "AI 활용 국제사회 이슈 분석",
        "AI 활용 국제사회 문제해결 프로젝트 1",
        "AI 활용 국제사회 문제해결 프로젝트 2",
        "4차 산업시대 글로벌 시티즌십",
        "미시·중시·거시적 글로벌 시티즌십 사례 1",
        "미시·중시·거시적 글로벌 시티즌십 사례 2",
        "미시·중시·거시적 글로벌 시티즌십 사례 3",
        "AI 인성진단 및 자기이해 · 분석과 코칭",
        { topic: "글로벌시민 S-PIPES 휴먼인성개발 포럼", assignment: "사회적 책무 선택서답 평가 여부 확인" },
        { topic: "글로벌 시민인성 실천 프로젝트 설계", assignment: "통합 리포트·기말평가 일정 확인" }
      ]),
      examMemo: "기말고사 20점이 안내되어 있고 13~15주차 기말 지필평가, 14주차 선택서답 평가가 함께 기재되어 있습니다. 실제 시험 주차와 범위는 담당 교수 공지에 따라 수정하세요.",
      courseMemo: ""
    },
    {
      id: "social-economy",
      order: 4,
      name: "사회적 경제의 이해와 지역사회",
      shortName: "사회적 경제의 이해와 지역사회",
      type: "general",
      color: "#c89aa5",
      professor: "김춘광",
      professorInfo: "",
      location: "본부 707",
      code: "0859802",
      section: "",
      credits: "2학점 · 이론 2",
      modality: "블렌디드 · 온라인 1시간 + 대면 1시간",
      meetingLabel: "화요일 8교시",
      meetings: [{ day: 2, start: 16, end: 17, room: "본부 707" }],
      description: "사회적경제의 등장 배경과 주요 조직을 이해하고, 자신이 사는 지역의 사회적경제 조직을 직접 조사·분석·발표하는 블렌디드 수업입니다.",
      goals: ["사회적경제의 기초 개념과 조직 유형 이해", "지역사회 문제와 사회적경제 조직의 역할 탐색", "현장 조사·사례 분석·발표를 통한 지역사회 적용 능력 향상"],
      textbooks: ["별도 주교재 없음 · 수업자료 PDF 제공 예정", "지속가능한 혁신공동체를 향한 실천전략", "비영리단체의 경영 · Peter F. Drucker", "사회적기업가정신 · 데이비드 본스타인·수전 데이비스"],
      grading: [{ label: "출석", value: 20 }, { label: "교과목 역량평가", value: 80 }],
      policies: ["매주 온라인 선행학습 1시간과 대면수업 1시간으로 진행", "온라인 강의 시청·수강확인 퀴즈·댓글 참여가 출석에 포함", "대면수업에서 토론과 프로젝트 참여 필요", "지역 기반 사회적경제 조직을 조사하고 최종 포트폴리오로 정리"],
      links: [],
      weeks: makeWeeks("2026-09-01", [
        "오리엔테이션 · 수업 운영 안내",
        "사회적경제의 등장 배경과 필요성",
        "사회적경제의 개념·정의·조직 유형",
        "IMF·신자유주의·양극화·금융위기",
        "자본주의와 시장경제의 부작용",
        "사회문제·사회적가치·제3섹터·미션과 비전",
        "소셜미션·영리조직·NPO·NGO",
        { topic: "중간고사", assignment: "온라인 강의·수강확인 퀴즈 여부 확인" },
        "사회적경제의 경제와 의사결정 원리",
        { topic: "상호작용 원리·경제 순환·시장", assignment: "지역 사회적경제 조직 선정·조사" },
        { topic: "사회적경제 사례 조사 발표 1", assignment: "사례 발표 자료" },
        { topic: "사회적경제 사례 조사 발표 2", assignment: "사례 발표·토론" },
        { topic: "사회적경제 사례 조사 발표 3", assignment: "현장 방문·관찰 내용 정리" },
        { topic: "사회적경제 사례 조사 발표 4", assignment: "최종 보고서·포트폴리오 준비" },
        { topic: "최종성과 평가 · 종강·기말고사", assignment: "최종 포트폴리오" }
      ]),
      examMemo: "8주차 중간고사, 15주차 기말고사 및 최종성과 평가가 안내되어 있습니다. 세부 시험 범위와 문항 형식은 교수 공지 후 입력하세요.",
      courseMemo: ""
    },
    {
      id: "human-way",
      order: 5,
      name: "사람다운 사람의 길",
      shortName: "사람다운 사람의 길",
      type: "general",
      color: "#d6a5b6",
      professor: "이동수",
      professorInfo: "",
      location: "본부 215",
      code: "0770850",
      section: "",
      credits: "1학점 · 이론 1",
      meetingLabel: "화요일 9교시",
      meetings: [{ day: 2, start: 17, end: 18, room: "본부 215" }],
      description: "기독교 인성교육의 핵심 덕목을 통해 이웃·사회·공동체와의 관계에서 사람답게 사는 길과 대인관계 역량을 배우는 수업입니다.",
      goals: ["기독교 인성의 핵심 덕목 이해", "공감·수용·존중·감사·겸손 등 대인관계 역량 강화", "공동체를 섬기고 시민의식을 실천하는 태도 형성"],
      textbooks: ["사람다운 사람 · 뷰리출판"],
      grading: [{ label: "출석", value: 20 }, { label: "교과목 역량평가", value: 80 }],
      policies: ["출석 평가는 학사 출석 기준에 따름", "8주차 정직 수업에서 필요 시 수시고사 가능", "15주차 대인관계 역량을 평가하는 논술형 기말고사"],
      links: [],
      weeks: makeWeeks("2026-09-01", [
        "강의 소개 · 설문조사",
        "사람다운 사람이란?",
        "역지사지로 공감능력 키우기",
        "자기 수용은 건강한 자존감의 기초",
        "존중하면 사람을 얻는다",
        "감사는 표현으로 완성된다",
        "겸손 · 자기보다 남을 낫게 여기고",
        { topic: "정직이 최선의 방책이다", assignment: "수시고사 여부 확인" },
        "절제의 미덕을 깨우라",
        "말은 인생의 핸들이다",
        "건강한 삶을 위한 마음 관리",
        "용서 · 마음의 감옥에서 자유를",
        "긍휼과 나눔 · 청지기 정신으로",
        "공동체 삶과 시민의식",
        { topic: "기말고사", detail: "대인관계 역량 논술 평가" }
      ]),
      examMemo: "8주차 수업에서 필요 시 수시고사가 있을 수 있습니다. 15주차에는 대인관계 역량을 평가하는 논술형 기말고사가 예정되어 있습니다.",
      courseMemo: ""
    },
    {
      id: "english-b",
      order: 6,
      name: "실전 영어회화(B)",
      shortName: "실전 영어회화",
      type: "general",
      color: "#c89ba1",
      professor: "WILLIAM JOSEPH GRECO",
      professorInfo: "",
      location: "진리 510",
      code: "0854721",
      section: "",
      credits: "2학점 · 이론 2",
      meetingLabel: "월요일 4교시",
      meetings: [{ day: 1, start: 12, end: 13, room: "진리 510" }],
      description: "다양한 주제의 대화·인터뷰·리서치와 짝·모둠 활동을 통해 실제 영어 의사소통 능력과 유창성을 기르는 회화 수업입니다.",
      goals: ["기본 영어회화 기술을 수준별로 향상", "자신 있게 영어로 말하고 생각을 표현", "듣기·말하기 능력을 실용영어에 응용", "실생활에서 자연스럽게 의사소통하는 능력 개발"],
      textbooks: ["Breakthrough Plus 3, 2nd Edition · Miles Craven", "Breakthrough Plus 3 Student Workbook, 2nd Edition"],
      grading: [{ label: "출석", value: 20 }, { label: "중간고사", value: 30 }, { label: "기말고사", value: 30 }, { label: "과제·발표", value: 20 }],
      policies: ["결석 4주 시 자동 F", "지각 3회는 결석 1회로 계산", "결강원은 결석일로부터 2주 이내 제출", "병결은 증빙서류를 첨부하고 학기 최대 2회 인정", "말하기 중심의 짝·모둠 토론 활동"],
      links: [],
      weeks: makeWeeks("2026-09-07", [
        "Orientation · 교재와 수업 활동 안내",
        "Unit 1 Memories · 기억에 관해 말하기",
        "Unit 2 Life changes · 삶을 바꾼 사건",
        "Unit 3 Viewpoints · 의견 표현하기",
        "Unit 4 Problems · 삶의 문제 말하기",
        "Unit 5 Thinking ahead · 미래 사건 예측",
        "Unit 6 Imagine · 미래 계획 말하기",
        { topic: "중간고사", detail: "Oral and written work · ONLINE 표기" },
        "Unit 7 My World · 사람·장소·사물",
        "Unit 8 Past events · 경험 말하기",
        "Unit 9 Feelings and Opinions",
        "Unit 10 What if...? · 소망과 가능성",
        "Unit 11 Work it out · 추론하기",
        "Unit 12 Looking back · 중요한 사건 회고",
        { topic: "기말고사", detail: "Oral and written work · ONLINE 표기" }
      ]),
      examMemo: "8주차 중간고사와 15주차 기말고사는 말하기·쓰기 평가이며 계획서에는 평가 장소가 ONLINE으로 표시되어 있습니다. 세부 문항과 접속 방식은 공지 확인이 필요합니다.",
      courseMemo: ""
    },
    {
      id: "unix",
      order: 7,
      name: "유닉스시스템",
      shortName: "유닉스 시스템",
      type: "major",
      color: "#789bd8",
      professor: "이승화",
      professorInfo: "",
      location: "본부 210",
      code: "0219401",
      section: "",
      credits: "3학점 · 이론 2 · 실습 2",
      meetingLabel: "월요일 7-9교시",
      meetings: [{ day: 1, start: 15, end: 18, room: "본부 210" }],
      description: "유닉스 운영체제의 운용·관리, C 프로그래밍과 셸 스크립트, APM 웹 서버 구축을 학습하고 팀 프로젝트로 웹 서비스를 구현하는 전공 수업입니다.",
      goals: ["운영체제와 유닉스 시스템의 기본 원리 이해", "유닉스 시스템 운용·사용자·파일·프로세스 관리 기술 습득", "C·셸 스크립트·웹 서버를 활용한 응용 기술 습득"],
      textbooks: ["유닉스 이론과 실습 · 윤소정·이종원 · 한빛아카데미", "리눅스 시스템 원리와 실제 · 창병모", "첫 수업 기초 테스트 후 교재 확정 예정"],
      grading: [{ label: "출석", value: 10 }, { label: "중간고사", value: 20 }, { label: "기말고사", value: 25 }, { label: "프로젝트", value: 45 }],
      policies: ["첫 수업 참석 필수", "지각·조퇴 1회당 출석점수 1점 감점, 결석 1회당 3점 감점", "결석 4회이면 F", "4~5명 팀으로 유닉스 환경의 자유 주제 웹 서비스 개발", "프로젝트는 창의력·활동 참여·팀 기여도와 상호평가를 반영"],
      links: [],
      weeks: makeWeeks("2026-09-07", [
        { topic: "Orientation · 운영체제 기본 개념", detail: "수업 소개와 수강자 기초 테스트", assignment: "첫 수업 필수 참석" },
        "유닉스 개요 · Ubuntu 설치와 환경 탐색",
        "유닉스 기본 명령어 1 · 디렉터리·파일 관리",
        { topic: "유닉스 기본 명령어 2", detail: "사용자 계정·권한·프로세스 관리", assignment: "팀 구성" },
        "유닉스 기본 명령어 3 · 파이프와 리다이렉션",
        "vi 편집기 1 · 기본 명령어와 gcc",
        "vi 편집기 2 · C 예제와 셸 스크립트",
        { topic: "중간고사 · 1~7주차 정리", detail: "서답형 시험" },
        "웹 서버 개요 · APM 설치와 운용",
        "HTML·PHP 기본 문법",
        "HTML·PHP 활용 예제",
        "MySQL 기본 문법",
        "PHP-MySQL 연동 · 웹 서비스 구현 1",
        { topic: "웹 서비스 구현 2 · 결과 발표", assignment: "팀 프로젝트 결과 발표·보고서" },
        { topic: "기말고사 · 9~14주차 정리", detail: "서답형 시험" }
      ]),
      examMemo: "8주차 중간고사는 1~7주차, 15주차 기말고사는 9~14주차가 범위이며 모두 서답형입니다. 14~15주차에는 팀 프로젝트 결과 발표·보고서 평가도 함께 진행됩니다.",
      courseMemo: ""
    },
    {
      id: "future-tech",
      order: 8,
      name: "미래사회와 과학기술",
      shortName: "미래사회와 과학기술",
      type: "online",
      color: "#70b5a8",
      professor: "조용철",
      professorInfo: "",
      location: "온라인 수업",
      code: "3003601",
      section: "",
      credits: "2학점 · 이론 2",
      modality: "완전 사이버강의 · 원격수업 100%",
      meetingLabel: "사이버강의",
      meetings: [],
      description: "인공지능·로봇·바이오·기후변화 등 미래사회의 문제를 사례 중심으로 살피고, 과학기술이 사회에 가져올 변화와 해결 방향을 프로젝트로 탐색하는 완전 온라인 수업입니다.",
      goals: ["4차 산업혁명 시대의 사회 변화와 과학기술 현황 이해", "과학기술이 미래사회 문제 해결에 적용되는 방식 예측", "새로운 기술의 변화와 예상 문제점을 분석하고 해결 방안 모색"],
      textbooks: ["2024 과학기술통계백서", "2024 생명공학백서", "2024 인터넷백서", "2024 양자정보기술백서", "미래사회와 과학기술 강의자료"],
      grading: [{ label: "출석", value: 10 }, { label: "프로젝트", value: 40 }, { label: "논술 역량평가", value: 45 }, { label: "자기평가", value: 5 }],
      policies: ["개강 첫 주부터 원격수업 100%", "사이버캠퍼스에서 온라인 수강 여부로 출석 체크", "각 강의 지정 수강 기간은 일주일", "수강 기간이 끝날 때 미수강이면 결석 처리", "지각 3회는 결석 1회로 계산"],
      links: [],
      weeks: makeWeeks("2026-09-01", [
        "미래사회와 과학기술 개요와 의의",
        "저출산과 바이오공학 · 고령화와 제론테크",
        "자살 문제와 AI · 불평등과 정보통신",
        { topic: "지방소멸과 초고속열차 · 스마트시티", assignment: "프로젝트 계획보고서" },
        "교통 문제와 자율자동차 · 프롭테크",
        "사회안전과 빅데이터 · 범죄와 IoT",
        "사이버보안과 블록체인 · 테러리즘과 드론",
        { topic: "노동과 로봇공학 · 교육과 에듀테크", assignment: "프로젝트 1차 보고서 · 역량평가" },
        "저성장과 미디어 · 글로벌과 모바일",
        "질병 치료와 나노기술 · 핵융합기술",
        "환경 문제와 신소재 · 기후변화와 친환경에너지",
        { topic: "남북 문제와 스마트팜 · 통일과 유전공학", assignment: "프로젝트 2차 보고서" },
        "국제분쟁과 3D 프린팅 · 우주개발과 우주공학",
        { topic: "미래사회·과학기술의 문제와 과제", assignment: "프로젝트 최종보고서 · 자기평가" },
        { topic: "미래사회와 과학기술 전망 · 기말고사", assignment: "논술형 역량평가" }
      ]),
      examMemo: "8주차와 15주차에 논술형 역량평가가 안내되어 있습니다. 기말고사는 미래사회와 과학기술을 분석하는 논술형 2문제 이상이며 사이버캠퍼스 시험게시판에서 진행될 예정입니다.",
      courseMemo: ""
    },
    {
      id: "bible-human",
      order: 9,
      name: "성경과 인간이해2",
      shortName: "성경과 인간이해2",
      type: "online",
      color: "#76aa98",
      professor: "문유미",
      professorInfo: "",
      location: "온라인 수업",
      code: "0852805",
      section: "",
      credits: "1학점 · 이론 1",
      modality: "사이버강의 · 사용자 시간표 기준",
      meetingLabel: "사이버강의",
      meetings: [],
      description: "신약성경을 통해 인간과 공동체를 이해하고, 감정 관리와 대인관계·공동체 섬김 역량을 기르는 수업입니다. 사용자 제공 시간표에 따라 사이버강의로 분류했습니다.",
      goals: ["자신의 감정을 통제·관리·조절하는 자기관리 역량 개발", "신약성경의 인간 이해를 바탕으로 대인관계와 공동체 섬김 학습", "장단기 목표 수립과 책임 있는 공동체 구성원 태도 형성"],
      textbooks: ["바이블로드 신약 · 뷰리출판", "성경전서 · 대한성서공회", "개혁주의 스터디바이블"],
      grading: [{ label: "출석", value: 20 }, { label: "수시평가", value: 40 }, { label: "기말시험", value: 40 }],
      policies: ["출석 평가는 학사 기준에 따름", "8주차 또는 수시에 공동체 섬김 경험 관련 평가 가능", "수시고사·과제·발표·토론이 역량평가에 포함", "계획서에는 온라인 방식이 명시되지 않았으므로 실제 수강·평가 방식은 공지 확인 필요"],
      links: [],
      weeks: makeWeeks("2026-09-01", [
        "오리엔테이션",
        "신약배경사 · 복음전파를 위한 준비",
        "마태복음 · 복음과 하나님 나라",
        "마가복음 · 예수 그리스도의 복음",
        "누가복음 · 세속적 순환고리 끊기",
        "요한복음·요한서신 · 하나님의 아들 예수",
        "사도행전 · 복음전파와 바울의 선교여행",
        { topic: "로마서 · 믿음과 은혜로 얻은 구원", assignment: "공동체 섬김 1차 평가 여부 확인" },
        "고린도전후서 · 문화적 충돌과 이웃사랑",
        "갈라디아서 외 바울서신 · 신앙의 실천",
        "디모데전후서·디도서 · 소명과 사명",
        "히브리서·공동서신 · 거룩과 화평",
        "요한계시록 · 구속사의 완성과 종말론적 삶",
        "성경을 어떻게 읽을 것인가",
        { topic: "기말시험", detail: "논술형 평가" }
      ]),
      examMemo: "8주차 또는 수시에 공동체 섬김 관련 평가가 있을 수 있고, 15주차에는 논술형 기말시험이 예정되어 있습니다. 온라인 시험 여부와 세부 범위는 공지 확인이 필요합니다.",
      courseMemo: ""
    }
  ];

  window.DEFAULT_SEMESTER_DATA = {
    version: 3,
    meta: {
      year: 2026,
      term: "2학기",
      startDate: "2026-09-01",
      endDate: "2026-12-18"
    },
    courses,
    chapels: [
      { id: "chapel-b", name: "채플과 섬김", division: "01", day: 1, start: 11, end: 12, period: "3교시", area: "B", seat: "105", location: "백석홀 대강당", color: "#d8a2ad" },
      { id: "chapel-a", name: "채플과 섬김", division: "04", day: 1, start: 13, end: 14, period: "5교시", area: "A", seat: "132", location: "백석홀 대강당", color: "#d8a2ad" }
    ],
    tasks: [
      { id: "python-practice-1", courseId: "python", title: "실습과제 1", type: "assignment", dueDate: "2026-09-15", notes: "3주차 과제 · 실제 마감 시각 확인", completed: false },
      { id: "python-practice-2", courseId: "python", title: "실습과제 2", type: "assignment", dueDate: "2026-10-06", notes: "6주차 과제", completed: false },
      { id: "python-competency", courseId: "python", title: "전공문제해결능력 과제 평가", type: "assignment", dueDate: "2026-10-20", notes: "계획서의 8주차 평가 · 세부 공지 확인", completed: false },
      { id: "python-practice-3", courseId: "python", title: "실습과제 3", type: "assignment", dueDate: "2026-11-03", notes: "10주차 과제", completed: false },
      { id: "python-practice-4", courseId: "python", title: "실습과제 4", type: "assignment", dueDate: "2026-12-01", notes: "14주차 과제", completed: false },
      { id: "startup-idea", courseId: "startup", title: "나만의 창업 아이디어 기획", type: "assignment", dueDate: "", notes: "중간고사 이전 제출 · 실제 마감일 입력", completed: false },
      { id: "startup-ethics", courseId: "startup", title: "윤리적 의사결정 사례 연구", type: "assignment", dueDate: "", notes: "중간고사 이후 제출", completed: false },
      { id: "startup-report", courseId: "startup", title: "개인 레포트", type: "assignment", dueDate: "", notes: "주제·마감 공지 확인", completed: false },
      { id: "startup-portfolio", courseId: "startup", title: "주차별 포트폴리오 정리", type: "review", dueDate: "", notes: "매주차 과정평가", completed: false },
      { id: "ai-diagnosis", courseId: "ai-citizen", title: "S-PIPES 인성 자기진단", type: "assignment", dueDate: "", notes: "1~4주차 진단·설계 단계", completed: false },
      { id: "ai-goal", courseId: "ai-citizen", title: "개인 인성 개발 목표 작성", type: "assignment", dueDate: "", notes: "글로벌 시티즌 정체성 선언 포함", completed: false },
      { id: "ai-project", courseId: "ai-citizen", title: "AI 활용 문제해결 프로젝트", type: "assignment", dueDate: "", notes: "5~12주차 개인·팀 프로젝트", completed: false },
      { id: "ai-forum", courseId: "ai-citizen", title: "인성 특강·포럼 참여", type: "other", dueDate: "2026-12-01", notes: "14주차 일정 확인", completed: false },
      { id: "ai-report", courseId: "ai-citizen", title: "개인·팀 통합 리포트", type: "assignment", dueDate: "", notes: "13~15주차 성찰·통합 단계", completed: false },
      { id: "social-online", courseId: "social-economy", title: "매주 온라인 선행강의 시청", type: "online", dueDate: "", notes: "대면수업 전 시청 · 주간 마감일 확인", completed: false },
      { id: "social-quiz", courseId: "social-economy", title: "수강확인 퀴즈·댓글 참여", type: "quiz", dueDate: "", notes: "온라인 출석에 포함", completed: false },
      { id: "social-pick", courseId: "social-economy", title: "지역 사회적경제 조직 선정", type: "assignment", dueDate: "2026-11-03", notes: "현장 조사 대상 정하기", completed: false },
      { id: "social-field", courseId: "social-economy", title: "현장 방문·사례 분석", type: "assignment", dueDate: "", notes: "11~14주차 발표 준비", completed: false },
      { id: "social-portfolio", courseId: "social-economy", title: "최종 보고서·포트폴리오", type: "assignment", dueDate: "2026-12-08", notes: "15주차 최종성과 평가", completed: false },
      { id: "human-book", courseId: "human-way", title: "교재 준비", type: "other", dueDate: "", notes: "사람다운 사람 · 뷰리출판", completed: false },
      { id: "human-quiz", courseId: "human-way", title: "8주차 수시고사 여부 확인", type: "quiz", dueDate: "2026-10-20", notes: "정직 수업에서 필요 시 실시", completed: false },
      { id: "english-assignment", courseId: "english-b", title: "과제·발표 공지 확인", type: "assignment", dueDate: "", notes: "평가 20점 · 구체 일정 미기재", completed: false },
      { id: "english-review", courseId: "english-b", title: "주차별 표현 복습", type: "review", dueDate: "", notes: "교재 대화문·어휘·문형", completed: false },
      { id: "unix-first", courseId: "unix", title: "첫 수업 참석·기초 테스트", type: "other", dueDate: "2026-09-07", notes: "첫 수업 참석 필수", completed: false },
      { id: "unix-team", courseId: "unix", title: "팀 프로젝트 주제·팀 구성", type: "assignment", dueDate: "", notes: "4~5명 · 유닉스 웹 서비스", completed: false },
      { id: "unix-presentation", courseId: "unix", title: "프로젝트 결과 발표·보고서", type: "assignment", dueDate: "2026-12-07", notes: "14주차 발표회", completed: false },
      { id: "future-weekly", courseId: "future-tech", title: "이번 주 온라인 강의 시청", type: "online", dueDate: "", notes: "각 강의 수강 기간 1주 · 실제 마감일 입력", completed: false },
      { id: "future-plan", courseId: "future-tech", title: "프로젝트 계획보고서", type: "assignment", dueDate: "2026-09-22", notes: "제목·목적·주제 선정 이유", completed: false },
      { id: "future-report-1", courseId: "future-tech", title: "프로젝트 1차 보고서", type: "assignment", dueDate: "2026-10-20", notes: "주요 내용·논리적 근거·자료", completed: false },
      { id: "future-report-2", courseId: "future-tech", title: "프로젝트 2차 보고서", type: "assignment", dueDate: "2026-11-17", notes: "분석 결과·전망·시사점", completed: false },
      { id: "future-final-report", courseId: "future-tech", title: "프로젝트 최종보고서", type: "assignment", dueDate: "2026-12-01", notes: "성과 환류·느낀 점·자기평가", completed: false },
      { id: "bible-weekly", courseId: "bible-human", title: "이번 주 사이버강의 시청", type: "online", dueDate: "", notes: "실제 마감일을 확인해 입력", completed: false },
      { id: "bible-service", courseId: "bible-human", title: "공동체 섬김 경험 정리", type: "assignment", dueDate: "2026-10-20", notes: "8주차 또는 수시 평가 가능", completed: false }
    ],
    exams: [
      { id: "exam-python-8", courseId: "python", title: "전공문제해결능력 과제 평가", type: "other", date: "2026-10-20", location: "실습실", range: "파이썬을 활용한 전공 문제 해결", criteria: "동료평가 · 실제 세부 기준 확인" },
      { id: "exam-python-15", courseId: "python", title: "실기 평가", type: "final", date: "2026-12-08", location: "실습실", range: "파이썬 응용과 Pandas 데이터 활용", criteria: "창의융합적사고·전공지식적용능력" },
      { id: "exam-startup-mid", courseId: "startup", title: "중간고사", type: "midterm", date: "2026-10-20", location: "강의실", range: "윤리경영 이해", criteria: "논술형" },
      { id: "exam-startup-final", courseId: "startup", title: "기말고사", type: "final", date: "2026-12-08", location: "강의실", range: "윤리경영의 전망과 과제", criteria: "논술형 · 개인 레포트 합산 배점 확인" },
      { id: "exam-ai-final", courseId: "ai-citizen", title: "기말평가", type: "final", date: "2026-12-08", location: "강의실", range: "AI 인성과 글로벌 시티즌십", criteria: "14주차 선택서답·13~15주차 지필평가 관계 확인" },
      { id: "exam-social-mid", courseId: "social-economy", title: "중간고사", type: "midterm", date: "2026-10-20", location: "강의실", range: "1~7주차 사회적경제 기초", criteria: "세부 형식 공지 확인" },
      { id: "exam-social-final", courseId: "social-economy", title: "기말고사·최종성과 평가", type: "final", date: "2026-12-08", location: "강의실", range: "사회적경제 사례 조사와 학습성과", criteria: "최종 포트폴리오 포함" },
      { id: "exam-human-final", courseId: "human-way", title: "기말고사", type: "final", date: "2026-12-08", location: "강의실", range: "기독교 인성 덕목과 대인관계", criteria: "논술형" },
      { id: "exam-english-mid", courseId: "english-b", title: "중간고사", type: "midterm", date: "2026-10-26", location: "ONLINE 표기", range: "Unit 1~6 중심", criteria: "Oral and written work" },
      { id: "exam-english-final", courseId: "english-b", title: "기말고사", type: "final", date: "2026-12-14", location: "ONLINE 표기", range: "Unit 7~12 중심", criteria: "Oral and written work" },
      { id: "exam-unix-mid", courseId: "unix", title: "중간고사", type: "midterm", date: "2026-10-26", location: "강의실", range: "1~7주차", criteria: "서답형" },
      { id: "exam-unix-final", courseId: "unix", title: "기말고사", type: "final", date: "2026-12-14", location: "강의실", range: "9~14주차", criteria: "서답형" },
      { id: "exam-future-8", courseId: "future-tech", title: "역량평가", type: "midterm", date: "2026-10-20", location: "사이버캠퍼스", range: "미래사회 문제 분석", criteria: "논술형 · 프로젝트 1차 보고서와 함께 진행" },
      { id: "exam-future-final", courseId: "future-tech", title: "기말고사", type: "final", date: "2026-12-08", location: "사이버캠퍼스 시험게시판", range: "미래사회와 과학기술 전망", criteria: "논술형 2문제 이상" },
      { id: "exam-bible-final", courseId: "bible-human", title: "기말시험", type: "final", date: "2026-12-08", location: "온라인 방식 확인 필요", range: "신약성경과 공동체 섬김", criteria: "논술형" }
    ],
    customEvents: []
  };
})();
